### ISSUE TITLE
BUG: PTO Tracker not equal to Freshbooks Accrued Time Off

### ISSUE THREAD

**Issue by ryangwilson** [bitovians/pto#12]
<img width="853" alt="screen shot 2019-01-22 at 11 25 24 am" src="https://user-images.githubusercontent.com/4571457/51550501-71576480-1e3a-11e9-900f-72bd371c4ebc.png">

<img width="269" alt="screen shot 2019-01-22 at 11 39 37 am" src="https://user-images.githubusercontent.com/4571457/51550502-71576480-1e3a-11e9-96f0-4faec7eb9f9d.png">

This is the link to my Google Sheets that is accurate to the Freshbooks information:
https://docs.google.com/spreadsheets/d/1KU3gN5LI85u1Xiyzxg2mQEi-j5f8fdEYgVm8QVXiVfs/edit?usp=sharing

This is the link to the Freshbooks Accrued Time Off data

**Comment by mjstahl** [comment]
This is not inaccurate, but bad UX. In the application the accrued hours are added after the month is finished. The spread sheet adds them in-line with the current month. 

I think this can be corrected by adding the accrued hours for the current month instead of waiting for the User to access the app in the following month.

**Comment by mjstahl** [comment]
I think this can be fixed by changing https://github.com/bitovians/pto/blob/master/components/dashboard/dashboard.js#L91
from `let m = 1` to `let m = 0`. 

For example, `new Date().getMonth()` for June would return 5 so that loop will iterate 5 times (1, 2, 3, 4, 5) where, to be inline with the spreadsheet, should include the current month which mean it should accrue for 6 months assuming a month of June.
